// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-web/repository"
	"go-web/service"
)

// Injectors from inject_service.go:

func InitUserService() *service.UserService {
	userDao := repository.NewUserDao()
	userService := service.NewUserService(userDao)
	return userService
}

func InitSysService() *service.SysService {
	sysService := service.NewSysService()
	return sysService
}
